### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by pbittyscu** [BadPirate/pgewall#4]
Hi Kevin - So excited about this tool! I'm also a software engineer and using javascript, python currently while scala, and java have been historical languages. 

I tried connecting to Enphase Energy site and received the error: "Unexpected token < in JSON at position 0". I did notice that when I logged into my Enphase Energy account, that PGE-Wall is an application that has access.
I saw the other issue you logged 10 days ago that is similar and it looked like the workaround is to not use the solar simulator. I don't think this applies though if you check the Net Energy Metering though.

Thanks for your work on this. I may be able to help out. I'll download the code and see if I can figure something out
<img width="779" alt="Screenshot 2020-10-25 at 10 42 22 AM" src="https://user-images.githubusercontent.com/19670263/97114662-13128200-16af-11eb-825c-de27510830dc.png">
. 

Thanks again, Patrick

**Comment by pbittyscu** [comment]
It's looking like the api.enphasenergy.com api isn't working with the "demo" username and key curl found on their "quick start" guide: https://developer.enphase.com/docs/quickstart.html
`curl -v "https://api.enphaseenergy.com/api/v2/systems/67/summary?key=96a7de32fabc1dd8ff68ec43eca21c06&user_id=4d7a45774e6a41320a"`

**Comment by BadPirate** [comment]
You should be able to manually import your enphase data with CSV upload,
until the issue regarding Enphase API has been sorted out.  Also, the
github doesn't have a real enphase API key in it, in order to anything more
than try it yourself you'll need to register for a free dev key I think.
